# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: demo.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\"G\n\x0b\x44\x65moRequest\x12\x12\n\nvideo_path\x18\x01 \x01(\t\x12\x10\n\x08txt_path\x18\x02 \x01(\t\x12\x12\n\nmodel_path\x18\x03 \x01(\t\"t\n\x0c\x44\x65moResponse\x12\x11\n\tframe_idx\x18\x01 \x01(\x05\x12\x18\n\x10maskmem_features\x18\x02 \x03(\x02\x12\x17\n\x0fmaskmem_pos_enc\x18\x03 \x03(\x02\x12\x1e\n\x16maskmem_features_shape\x18\x04 \x03(\x05\x32\x36\n\nSamService\x12(\n\x07RunDemo\x12\x0c.DemoRequest\x1a\r.DemoResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEMOREQUEST']._serialized_start=14
  _globals['_DEMOREQUEST']._serialized_end=85
  _globals['_DEMORESPONSE']._serialized_start=87
  _globals['_DEMORESPONSE']._serialized_end=203
  _globals['_SAMSERVICE']._serialized_start=205
  _globals['_SAMSERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
